repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: lint
        name: Run ESLint
        entry: npm run lint
        language: system
        types: [javascript, typescript]
      - id: test
        name: Run Tests
        entry: npm test
        language: system
        types: [javascript, typescript]
