apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
          - name: agent
            containerPort: 50000
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
    disableCSRFProtection: true
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
  configurationAsCode:
    secret:
      name: jenkins-config
  groovyScripts:
    secret:
      name: jenkins-scripts
