# devops/gitlab/gitlab-runner-config.toml
concurrent = 2
check_interval = 0

[[runners]]
  name = "docker-runner"
  url = "http://gitlab.local/"
  token = "REPLACE_WITH_REAL_TOKEN"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "node:20"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
