apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxsim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxsim
  template:
    metadata:
      labels:
        app: taxsim
    spec:
      containers:
        - name: taxsim
          image: taxsim:dev   # or your DockerHub image if pushed
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
