# devops/k8s/base/service.yml
apiVersion: v1
kind: Service
metadata:
  name: taxsim
spec:
  selector:
    app: taxsim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
