name: CI/CD Pipeline (Local Minikube)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run tests / build check
      - name: Run tests
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: v1.34.0

      # Build image directly into Minikube
      - name: Build Docker image in Minikube
        run: |
          minikube image build -t taxsim:latest -f docker/Dockerfile .

      # Deploy manifests if not already applied
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/base/deployment.yml
          kubectl apply -f k8s/base/service.yml
          kubectl apply -f k8s/base/ingress.yml

      # Update image in deployment
      - name: Update deployment with new image
        run: |
          kubectl set image deployment/taxsim taxsim=taxsim:latest
          kubectl rollout status deployment/taxsim
